---@meta

---@class (exact) PackageData
---@field name string The name of the package
---@field os string? The operating system to install the package for, so if it doesn't match the current os, it doesn't
---install the package
---@field execName string? optional executable name of the package
---@field portage boolean? if true, install using portage
---@field mason boolean? if true, install using mason
---@field pacman boolean? if true, install using pacman
---@field aur boolean? if true, install using an aur helper
---@field apt boolean? if true, install using apt

---@class (exact) initModule the main init module
---@field _catagorizePackages function
---@field ensure_installed function
---@field _osData string
---@field _portagePackages string[]
---@field _portageCommand string
---@field _masonPackages string[]
---@field _masonCommand string
---@field _pacmanPackages string[]
---@field _pacmanCommand string
---@field _aurPackages string[]
---@field _aurCommand string
---@field _aurHelper string
---@field _aptPackages string[]
---@field _aptCommand string
